spring.application.name=car-rental

# Database connection properties for PostgreSQL and server port
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/carrental
spring.datasource.username=carrental
spring.datasource.password=carrental

# Hibernate properties
spring.jpa.hibernate.ddl-auto=validate

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml


# Jackson
spring.jackson.default-property-inclusion=non_null